<?php

namespace App\Http\Controllers;

use App\Models\Conversation;
use App\Services\chat\RagChatService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use OpenApi\Attributes as OA;

#[OA\Tag(name: 'Conversations', description: 'Management of chatbot IA discussions by project')]
class ConversationMessageController extends Controller
{
    public function __construct(
        private RagChatService $ragChatService,
    ) {}


    #[OA\Post(
        path: '/api/conversations/{conversation}/messages',
        summary: 'Post a question to the chatbot IA',
        description: "Send a question in a conversation. The backend searches for relevant code chunks in the project's repositories, then generates a response using the LLM. The question and response are stored in the database.",
        tags: ['Conversations'],
        security: [['sanctum' => []]],
        parameters: [
            new OA\Parameter(
                name: 'conversation',
                in: 'path',
                required: true,
                schema: new OA\Schema(type: 'string', format: 'uuid')
            ),
        ],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(
                required: ['question'],
                properties: [
                    new OA\Property(
                        property: 'question',
                        type: 'string',
                        maxLength: 2000,
                        example: 'how does the GitHub authentication work ?'
                    ),
                ]
            )
        ),
        responses: [
            new OA\Response(
                response: 201,
                description: 'RResponse generated by the assistant',
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: 'data', ref: '#/components/schemas/ConversationMessage'),
                    ]
                )
            ),
            new OA\Response(response: 401, description: 'unauthenticated'),
            new OA\Response(response: 422, description: 'question missing or invalid'),
        ]
    )]
    public function store(Request $request, Conversation $conversation): JsonResponse
    {
        $validated = $request->validate([
            'question' => 'required|string|max:2000',
        ]);

        $assistantMessage = $this->ragChatService->ask($conversation, $validated['question']);

        return response()->json([
            'data' => $assistantMessage,
        ], 201);
    }
}